package com.esmt.sn.schoolmanagement.models.enums;

public enum TypePrivilege {
    CREATE_ROLE,
    UPDATE_ROLE,
    DELETE_ROLE,
    READ_ROLE,

    CREATE_USER,
    READ_USER,
    UPDATE_USER,
    AFFECT_ROLE,
    DELETE_USER,

    CREATE_RUBRICS,
    READ_RUBRICS,
    UPDATE_RUBRICS,
    DELETE_RUBRICS,

    CREATE_SECTION,
    READ_SECTION,
    UPDATE_SECTION,
    DELETE_SECTION,

    CREATE_CLASSES,
    READ_CLASSES,
    UPDATE_CLASSES,
    DELETE_CLASSES,


    CREATE_STUDENT,
    CREATE_BIG_STUDENT,
    UPDATE_STUDENT,
    DELETE_STUDENT,
    READ_STUDENT,

    GENERATE_BULLETIN,
    READ_BULLETIN,
    UPDATE_BULLETIN,

    CREATE_NOTE,
    UPDATE_NOTE,
    CREATE_BIG_NOTE,
    READ_NOTE,

    CREATE_PAYMENT_STUDENT,
    READ_PAYMENT,

}
